/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include "stm32f469xx.h"
#include "stm32f469_gpio_driver.h"

void delay() {
	for (int i = 0; i < 1000000; i++);
}

int main(void)
{
	GPIO_PeriClockControl(GPIOD, ENABLE);
	GPIO_PeriClockControl(GPIOA, ENABLE);

	GPIO_Handle handle;

	handle.pGPIOx = GPIOA;
	handle.GPIO_PinConfig.GPIO_pin = GPIO_PIN_2;
	handle.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IR_FT;
	handle.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PUPD_NONE;
	handle.GPIO_PinConfig.GPIO_PinAltFunMode = 0x5U;
	GPIO_Init(&handle);

	handle.pGPIOx = GPIOA;
	handle.GPIO_PinConfig.GPIO_pin = GPIO_PIN_12;
	handle.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IR_FT;
	handle.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PUPD_NONE;
	handle.GPIO_PinConfig.GPIO_PinAltFunMode = 0x5U;
	GPIO_Init(&handle);

	for(;;) {
		if (GPIO_ReadPin(GPIOA, GPIO_PIN_0)) {
			GPIO_WriteToPin(GPIOD, GPIO_PIN_4, GPIO_PIN_SET);
		} else {
			GPIO_WriteToPin(GPIOD, GPIO_PIN_4, GPIO_PIN_RESET);
		}
	}
}
