/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include "stm32f469xx.h"

int main(void)
{

	for(;;) {
		GPIOA_PCLK_EN();
		GPIOA_PCLK_DI();
	};
}
